# Generated by Django 5.1.1 on 2024-10-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebrashopapp', '0003_alter_productimages_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
