# Generated by Django 5.1.1 on 2024-10-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebrashopapp', '0004_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
