# Generated by Django 5.1.1 on 2024-10-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebrashopapp', '0007_productsmodel_is_active_registermodel_address_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
