# Generated by Django 5.1.1 on 2024-10-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebrashopapp', '0009_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RohamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_frontend_user', 'Can access frontend without CSRF check')],
            },
        ),
    ]
