# Generated by Django 5.1.1 on 2024-11-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebrashopapp', '0010_rohammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='zebrashopapp.tag'),
        ),
    ]
